name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: my-service-id
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - uses: actions/checkout@v3
    - run: railway up --service=${{ env.SVC_ID }}
