# See the Dockerfile to see build steps
name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  Deploy-to-Railway:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - run: railway up --service=${{ vars.SVC_ID }}
