# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'
    - name: Download Templ
      run: go install github.com/a-h/templ/cmd/templ@latest
    - name: Build
      run: |
        templ generate
    - uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: my-artifact
        path: .
  test:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'
    - name: Version
      run: go version
    - name: Download Templ
      run: go install github.com/a-h/templ/cmd/templ@latest
    - name: Build
      run: |
        templ generate
        go build
        ls -la
    - name: Tidy
      run: go mod tidy
    - name: Test
      run: go test -v ./...
  build:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: Build
      run: |
        go build
