# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'
    - name: Version
      run: go version
    - name: Download Templ
      run: go install github.com/a-h/templ/cmd/templ@latest
    - name: Build
      run: |
        templ generate
        go build -v ./...
    - name: Tidy
      run: go mod tidy
    - name: Test
      run: go test -v ./...
    - uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: my-artifact
        path: ./backend
  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "Artifact ID from previous job is $OUTPUT1"
